#
# Copyright (c) 2019, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: osb-atp-demo-1
spec:
  clusterServiceClassExternalName: atp-service
  clusterServicePlanExternalName: standard
  parameters:
    name: osbdemo2
    compartmentId: "ocid1.compartment.oc1..aaaaaaaar6fwhr5nz65maujzmzplvrlllol5buxyjyadmextzig3noeolfya"
    dbName: osbdemo2
    cpuCount: 1
    storageSizeTBs: 1
    licenseType: NEW
    autoScaling: false
    freeFormTags:
      testtag: demo
#   definedTags:
#     your-tag-namespace:
#       your-defined-key: some_value
  parametersFrom:
    - secretKeyRef:
        name: atp-secret
        key: password
